name: Run Tests
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - uses: actions/checkout@v2

      - name: Run Tests
        run: |
          dotnet test --logger "nunit;logfilepath=test-results.xml"
          
      - uses: MirageNet/nunit-reporter@v1.0.11
        if: always()
        with:
          path: test-results.xml
          access-token: ${{ secrets.GITHUB_TOKEN }}
